#preload = /home/predo/wallpaper/walpaper1.jpg
#preload = /home/predo/wallpaper/walpaper2.jpg
#wallpaper = DP-1,/home/predo/wallpaper/walpaper1.jpg
#wallpaper = HDMI-A-1,/home/predo/wallpaper/walpaper2.jpg
preload = /home/predo//wallpaper/default.jpg
wallpaper = ,/home/predo//wallpaper/default.jpg
splash = false
