# Configuração Geral
general {
    hide_cursor = true      # Esconde o cursor do mouse
}

# Widget de Fundo
background {
    monitor =
    path = screenshot       # Usa uma captura de tela do momento como fundo
    blur_passes = 2          # Quantidade de desfoque
    blur_size = 7            # Intensidade do desfoque
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
}

# Widget do Campo de Senha
input-field {
    monitor =
    size = 300, 50           # Largura, Altura
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(151515, 151515, 151515, 1.0)
    inner_color = rgba(200, 200, 200, 1.0)
    font_color = rgba(10, 10, 10, 1.0)
    font_size = 20
    placeholder_text = <span foreground="##cdd6f4">Digite a senha...</span>  # Texto interno
    fade_on_empty = true
    rounding = -1            # -1 para bordas completamente arredondadas
    check_color = rgba(204, 136, 34, 1.0)
    fail_color = rgba(204, 34, 34, 1.0)  # Cor quando a senha está errada
    fail_text = <span foreground="##f38ba8">Senha incorreta! ($ATTEMPTS)</span> # Texto de erro
    position = 0, -20
    halign = center
    valign = center
}

# Widget de Relógio
label {
    monitor =
    text = $TIME              # Mostra a hora atual
    color = rgba(255, 255, 255, 1.0)
    font_size = 80
    font_family = JetBrains Mono
    position = 0, 150
    halign = center
    valign = center
}

# Widget de Saudação
label {
    monitor =
    text = Olá, $USER         # Mostra o nome do usuário
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    position = 0, 50
    halign = center
    valign = center
}
